### ISSUE TITLE
"undefined local variable or method `admin" after Update

### ISSUE THREAD

**Issue by snooptl** [codevise/pageflow#1137]
I tried to update an outdated Pageflow-App (0.11.3) to the most current Version (v13.6) and followed the Update-Wikipage and the Changelog-Files to the best of my knowledge. 

However I still encounter the error below. Is it maybe related to the change in the AbilityMixin mentioned in the [Changelog of v13](https://github.com/codevise/pageflow/blob/13-0-stable/CHANGELOG.md)? I am grateful for any help or hints into the right direction.

I attached a full Stacktrace and the content of `app/models/ability.rb`

![Bildschirmfoto 2019-03-12 um 09 41 23](https://user-images.githubusercontent.com/48472663/54186191-18f02b00-44ab-11e9-8f9b-57b2f19ab280.png)

```ruby
class Ability¬
   include CanCan::Ability
   include Pageflow::AbilityMixin
 
   def initialize(user)
      # Setup abilities for Pageflow models
      pageflow_default_abilities(user)
  
      # Allow signed-in users to view the admin dashboard
      can :read, ActiveAdmin::Page, :name => "Dashboard"
   end
end
```

```
activemodel (5.2.0) lib/active_model/attribute_methods.rb:430:in `method_missing'
pageflow (13.6.0) lib/pageflow/user_mixin.rb:32:in `admin?'
pageflow (13.6.0) app/policies/pageflow/account_policy.rb:13:in `resolve'
pageflow (13.6.0) lib/pageflow/ability_mixin.rb:10:in `pageflow_default_abilities'
app/models/ability.rb:7:in `initialize'
activeadmin (1.3.1) lib/active_admin/cancan_adapter.rb:31:in `new'
activeadmin (1.3.1) lib/active_admin/cancan_adapter.rb:31:in `initialize_cancan_ability'
activeadmin (1.3.1) lib/active_admin/cancan_adapter.rb:19:in `cancan_ability'
activeadmin (1.3.1) lib/active_admin/cancan_adapter.rb:15:in `authorized?'
activeadmin (1.3.1) lib/active_admin/base_controller/authorization.rb:38:in `authorized?'
activeadmin (1.3.1) lib/active_admin/base_controller/authorization.rb:54:in `authorize!'
activeadmin (1.3.1) lib/active_admin/page_controller.rb:25:in `authorize_access!'
activesupport (5.2.0) lib/active_support/callbacks.rb:426:in `block in make_lambda'
activesupport (5.2.0) lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
actionpack (5.2.0) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
activesupport (5.2.0) lib/active_support/callbacks.rb:199:in `block in halting'
activesupport (5.2.0) lib/active_support/callbacks.rb:513:in `block in invoke_before'
activesupport (5.2.0) lib/active_support/callbacks.rb:513:in `each'
activesupport (5.2.0) lib/active_support/callbacks.rb:513:in `invoke_before'
activesupport (5.2.0) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.2.0) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.0) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.0) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.0) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.0) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.0) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.0) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.0) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.0) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.0) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.0) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.0) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.0) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.0) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.0) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.0) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.0) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.0) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.0) lib/action_dispatch/routing/route_set.rb:840:in `call'
http_accept_language (2.1.1) lib/http_accept_language/middleware.rb:14:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.0.6) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.6) lib/rack/etag.rb:25:in `call'
rack (2.0.6) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.6) lib/rack/head.rb:12:in `call'
actionpack (5.2.0) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.6) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.6) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/cookies.rb:670:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.0) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.0) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.2.0) lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by tf** [comment]
The `admin` flag was [added to the `User` model](https://github.com/codevise/pageflow/blob/v12.0.0/db/migrate/20160504093145_replace_role_and_account_on_user.rb) in 12.0. The error looks like you might be missing a migration. Make sure all [migrations have been installed](https://github.com/codevise/pageflow/wiki/Updating-Pageflow#database-migrations) into you host application.

**Comment by snooptl** [comment]
I somehow missed the Info about the mandatory update to 12.2 first, although it is clearly stated in the [v13-Changelog](https://github.com/codevise/pageflow/blob/13-0-stable/CHANGELOG.md). Downgrading to v12.2, running the migrations and update to 13.6 again fixed the problem.

Thank you :)

**Comment by tf** [comment]
Happy to hear you figured it out! :+1:
