### ISSUE TITLE
Uglifier::Error: on assets:precompile

### ISSUE THREAD

**Issue by jp604** [codevise/pageflow#2169]
Hi, I am trying to update an old PageFlow installation.

I have been following the instructions outlined in https://github.com/codevise/pageflow/wiki/Updating-Pageflow

When moving from 15.2.2 to 15.3.0, the "rake assets:precompile" fails with an Uglifier error:
```
rake aborted!
Uglifier::Error: Unexpected token: punc ()). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).

```

After changing the file config/environments/production.rb

`config.assets.js_compressor = :uglifier --> config.assets.js_compressor = Uglifier.new(harmony: true)`

the "rake assets:precompile" processed the following files without issues:

```
/assets/react-server-465a1f59ed94e244bb0a4ac4681e16921ba4ef11abacd67be0eef77dae3fadb6.js
/assets/react-server-465a1f59ed94e244bb0a4ac4681e16921ba4ef11abacd67be0eef77dae3fadb6.js.gz
/assets/components-7cfbf8c460289341e019bdda7707b0d28d7ead98a65f8cec7bf71e80789dd8b8.js
/assets/components-7cfbf8c460289341e019bdda7707b0d28d7ead98a65f8cec7bf71e80789dd8b8.js.gz
/assets/active_admin-f0f7154f1e0035bf0a231a8c7799758e4adb8c5a7ea7d93a0bf00b42b29df1a3.js
/assets/active_admin-f0f7154f1e0035bf0a231a8c7799758e4adb8c5a7ea7d93a0bf00b42b29df1a3.js.gz
/assets/pageflow_paged/vendor-e9832a76e1bcaf1c3a2973649e7b59e208337c9c245ac02796968c5650f7d0c7.js
/assets/pageflow_paged/vendor-e9832a76e1bcaf1c3a2973649e7b59e208337c9c245ac02796968c5650f7d0c7.js.gz
/assets/pageflow_paged/editor-6dd16d8d1443799cf55ac83f59d325c8292098d69a5625829da56afc46b904b3.js
/assets/pageflow_paged/editor-6dd16d8d1443799cf55ac83f59d325c8292098d69a5625829da56afc46b904b3.js.gz
/assets/pageflow_paged/frontend-62e08e97086b53cc151e41ee9ae6e38a8b1b6ea0e98270213e5d0d5ee2a4c9a9.js
/assets/pageflow_paged/frontend-62e08e97086b53cc151e41ee9ae6e38a8b1b6ea0e98270213e5d0d5ee2a4c9a9.js.gz

```

and then throws the follwing error:

```
rake aborted!
Uglifier::Error:
/home/ts_pageflow/.gem/ruby/2.6.0/gems/uglifier-4.2.1/lib/uglifier.rb:291:in `parse_result'
/home/ts_pageflow/.gem/ruby/2.6.0/gems/uglifier-4.2.1/lib/uglifier.rb:221:in `run_uglifyjs'
/home/ts_pageflow/.gem/ruby/2.6.0/gems/uglifier-4.2.1/lib/uglifier.rb:166:in `compile'
/home/ts_pageflow/.gem/ruby/2.6.0/gems/sprockets-3.7.5/lib/sprockets/compressing.rb:65:in `block in js_compressor='
/home/ts_pageflow/.gem/ruby/2.6.0/gems/sprockets-3.7.5/lib/sprockets/legacy_proc_processor.rb:31:in `call'
/home/ts_pageflow/.gem/ruby/2.6.0/gems/sprockets-3.7.5/lib/sprockets/processor_utils.rb:75:in `call_processor'
/home/ts_pageflow/.gem/ruby/2.6.0/gems/sprockets-3.7.5/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/home/ts_pageflow/.gem/ruby/2.6.0/gems/sprockets-3.7.5/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/home/ts_pageflow/.gem/ruby/2.6.0/gems/sprockets-3.7.5/lib/sprockets/processor_utils.rb:56:in `call_processors'
/home/ts_pageflow/.gem/ruby/2.6.0/gems/sprockets-3.7.5/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/home/ts_pageflow/.gem/ruby/2.6.0/gems/sprockets-3.7.5/lib/sprockets/loader.rb:60:in `block in load'
/home/ts_pageflow/.gem/ruby/2.6.0/gems/sprockets-3.7.5/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/home/ts_pageflow/.gem/ruby/2.6.0/gems/sprockets-3.7.5/lib/sprockets/loader.rb:44:in `load'
/home/ts_pageflow/.gem/ruby/2.6.0/gems/sprockets-3.7.5/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/home/ts_pageflow/.gem/ruby/2.6.0/gems/sprockets-3.7.5/lib/sprockets/cached_environment.rb:47:in `load'
/home/ts_pageflow/.gem/ruby/2.6.0/gems/sprockets-3.7.5/lib/sprockets/base.rb:66:in `find_asset'
/home/ts_pageflow/.gem/ruby/2.6.0/gems/sprockets-3.7.5/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/home/ts_pageflow/.gem/ruby/2.6.0/gems/sprockets-3.7.5/lib/sprockets/manifest.rb:134:in `block in find'
/home/ts_pageflow/.gem/ruby/2.6.0/gems/sprockets-3.7.5/lib/sprockets/manifest.rb:133:in `each'
/home/ts_pageflow/.gem/ruby/2.6.0/gems/sprockets-3.7.5/lib/sprockets/manifest.rb:133:in `find'
/home/ts_pageflow/.gem/ruby/2.6.0/gems/sprockets-3.7.5/lib/sprockets/manifest.rb:186:in `compile'
/home/ts_pageflow/.gem/ruby/2.6.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/task.rb:67:in `block (3 levels) in define'
/home/ts_pageflow/.gem/ruby/2.6.0/gems/sprockets-3.7.5/lib/rake/sprocketstask.rb:147:in `with_logger'
/home/ts_pageflow/.gem/ruby/2.6.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/task.rb:66:in `block (2 levels) in define'
/home/ts_pageflow/.gem/ruby/2.6.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/home/ts_pageflow/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
/home/ts_pageflow/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => assets:precompile
```

Do you have any idea what is causing this issue?

**Comment by tf** [comment]
Try using [`terser`](https://github.com/ahorek/terser-ruby) instead of `uglifier`.

**Comment by jp604** [comment]
Hi, terser worked perfectly.

Thank you for your advice,
JP
