### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by dklesev** [codevise/pageflow#447]
After setup and successful migration and seeding I'm getting this error on every page except *Dashboard* and *Profile Page*.

![](https://i.imgur.com/uYKwzIx.png)

Can someone help?

*INFO:*

```bash
$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux-gnu]

$ rails -v
Warning: Running `gem pristine --all` to regenerate your installed gemspecs (and deleting then reinstalling your bundle if you use bundle --path) will improve the startup performance of Spring.
Rails 4.1.0

$ mysql --version
mysql  Ver 14.14 Distrib 5.5.46, for debian-linux-gnu (x86_64) using readline 6.3

$ redis-server --version
Redis server v=3.0.5 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=6858bf999d2a6d98
```

Applied mysql2 fix from [#21544](https://github.com/rails/rails/issues/21544)

Some Log:

```bash
Started GET "/admin/entries" for xxx.xxx.xxx.xxx at 2015-11-29 04:20:50 +0000
Processing by Admin::EntriesController#index as HTML
  User Load (0.3ms)  SELECT  `users`.* FROM `users`  WHERE `users`.`id` = 1  ORDER BY `users`.`id` ASC LIMIT 1
  Pageflow::Entry Load (0.2ms)  SELECT `pageflow_entries`.* FROM `pageflow_entries` INNER JOIN `pageflow_memberships` ON `pageflow_entries`.`id` = `pageflow_memberships`.`entry_id` WHERE `pageflow_memberships`.`user_id` = 1
  Rendered /home/ubuntu/.bundler/ruby/2.2.0/active_admin-2385a54a15eb/app/views/active_admin/resource/index.html.arb (487.4ms)
Completed 500 Internal Server Error in 504ms

ActionView::Template::Error (undefined method `reorder' for nil:NilClass):
    1: insert_tag renderer_for(:index)
  /home/ubuntu/.bundler/ruby/2.2.0/active_admin-2385a54a15eb/lib/active_admin/helpers/collection.rb:11:in `collection_size'
  /home/ubuntu/.bundler/ruby/2.2.0/active_admin-2385a54a15eb/lib/active_admin/helpers/collection.rb:19:in `collection_is_empty?'
  /home/ubuntu/.bundler/ruby/2.2.0/active_admin-2385a54a15eb/lib/active_admin/views/pages/index.rb:44:in `items_in_collection?'
  /home/ubuntu/.bundler/ruby/2.2.0/active_admin-2385a54a15eb/lib/active_admin/views/pages/index.rb:48:in `build_collection'
  /home/ubuntu/.bundler/ruby/2.2.0/active_admin-2385a54a15eb/lib/active_admin/views/pages/index.rb:27:in `block in main_content'
  /home/ubuntu/.bundler/ruby/2.2.0/active_admin-2385a54a15eb/lib/active_admin/views/pages/index.rb:37:in `call'
  /home/ubuntu/.bundler/ruby/2.2.0/active_admin-2385a54a15eb/lib/active_admin/views/pages/index.rb:37:in `wrap_with_batch_action_form'
  /home/ubuntu/.bundler/ruby/2.2.0/active_admin-2385a54a15eb/lib/active_admin/views/pages/index.rb:25:in `main_content'
  /home/ubuntu/.bundler/ruby/2.2.0/active_admin-2385a54a15eb/lib/active_admin/views/pages/base.rb:87:in `block (2 levels) in build_main_content_wrapper'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
  arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:14:in `div'
  /home/ubuntu/.bundler/ruby/2.2.0/active_admin-2385a54a15eb/lib/active_admin/views/pages/base.rb:86:in `block in build_main_content_wrapper'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
  arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:14:in `div'
  /home/ubuntu/.bundler/ruby/2.2.0/active_admin-2385a54a15eb/lib/active_admin/views/pages/base.rb:85:in `build_main_content_wrapper'
  /home/ubuntu/.bundler/ruby/2.2.0/active_admin-2385a54a15eb/lib/active_admin/views/pages/base.rb:69:in `block in build_page_content'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
  arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:14:in `div'
  /home/ubuntu/.bundler/ruby/2.2.0/active_admin-2385a54a15eb/lib/active_admin/views/pages/base.rb:68:in `build_page_content'
  /home/ubuntu/.bundler/ruby/2.2.0/active_admin-2385a54a15eb/lib/active_admin/views/pages/base.rb:51:in `block (2 levels) in build_page'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
  arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:14:in `div'
  /home/ubuntu/.bundler/ruby/2.2.0/active_admin-2385a54a15eb/lib/active_admin/views/pages/base.rb:48:in `block in build_page'
  arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  /home/ubuntu/.bundler/ruby/2.2.0/active_admin-2385a54a15eb/lib/active_admin/views/pages/base.rb:47:in `build_page'
  /home/ubuntu/.bundler/ruby/2.2.0/active_admin-2385a54a15eb/lib/active_admin/views/pages/base.rb:10:in `build'
  pageflow (0.9.1) lib/active_admin/patches/views/pages/base.rb:5:in `build'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
  arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  /home/ubuntu/.bundler/ruby/2.2.0/active_admin-2385a54a15eb/app/views/active_admin/resource/index.html.arb:2:in `block in __home_ubuntu__bundler_ruby_______active_admin_____a__a__eb_app_views_active_admin_resource_index_html_arb___1400012177928594034_70188727050180'
  arbre (1.0.3) lib/arbre/context.rb:45:in `instance_eval'
  arbre (1.0.3) lib/arbre/context.rb:45:in `initialize'
  /home/ubuntu/.bundler/ruby/2.2.0/active_admin-2385a54a15eb/app/views/active_admin/resource/index.html.arb:1:in `new'
  /home/ubuntu/.bundler/ruby/2.2.0/active_admin-2385a54a15eb/app/views/active_admin/resource/index.html.arb:1:in `__home_ubuntu__bundler_ruby_______active_admin_____a__a__eb_app_views_active_admin_resource_index_html_arb___1400012177928594034_70188727050180'
  actionview (4.1.0) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.1.0) lib/active_support/notifications.rb:161:in `instrument'
  actionview (4.1.0) lib/action_view/template.rb:339:in `instrument'
  actionview (4.1.0) lib/action_view/template.rb:143:in `render'
  actionview (4.1.0) lib/action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'
  actionview (4.1.0) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (4.1.0) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.0) lib/active_support/notifications.rb:159:in `instrument'
  actionview (4.1.0) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionview (4.1.0) lib/action_view/renderer/template_renderer.rb:54:in `block in render_template'
  actionview (4.1.0) lib/action_view/renderer/template_renderer.rb:62:in `render_with_layout'
  actionview (4.1.0) lib/action_view/renderer/template_renderer.rb:53:in `render_template'
  actionview (4.1.0) lib/action_view/renderer/template_renderer.rb:17:in `render'
  actionview (4.1.0) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.1.0) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.1.0) lib/action_view/rendering.rb:99:in `_render_template'
  actionpack (4.1.0) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.1.0) lib/action_view/rendering.rb:82:in `render_to_body'
  actionpack (4.1.0) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.1.0) lib/action_controller/metal/renderers.rb:32:in `render_to_body'
  actionpack (4.1.0) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.1.0) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.1.0) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
  activesupport (4.1.0) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /usr/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  activesupport (4.1.0) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.1.0) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
  actionpack (4.1.0) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
  activerecord (4.1.0) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.1.0) lib/action_controller/metal/instrumentation.rb:40:in `render'
  /home/ubuntu/.bundler/ruby/2.2.0/active_admin-2385a54a15eb/lib/active_admin/resource_controller/actions.rb:13:in `block (2 levels) in index'
  actionpack (4.1.0) lib/action_controller/metal/responder.rb:236:in `call'
  actionpack (4.1.0) lib/action_controller/metal/responder.rb:236:in `default_render'
  actionpack (4.1.0) lib/action_controller/metal/responder.rb:165:in `to_html'
  responders (1.0.0) lib/responders/flash_responder.rb:104:in `to_html'
  actionpack (4.1.0) lib/action_controller/metal/responder.rb:158:in `respond'
  actionpack (4.1.0) lib/action_controller/metal/responder.rb:151:in `call'
  actionpack (4.1.0) lib/action_controller/metal/mime_responds.rb:400:in `respond_with'
  inherited_resources (1.4.1) lib/inherited_resources/actions.rb:7:in `index'
  /home/ubuntu/.bundler/ruby/2.2.0/active_admin-2385a54a15eb/lib/active_admin/resource_controller/actions.rb:11:in `index'
  actionpack (4.1.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.1.0) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.0) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.0) lib/active_support/callbacks.rb:229:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.0) lib/active_support/callbacks.rb:86:in `call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.1.0) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.0) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.0) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.0) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.1.0) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.1.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.0) lib/action_controller/metal.rb:231:in `block in action'
  actionpack (4.1.0) lib/action_dispatch/routing/route_set.rb:80:in `call'
  actionpack (4.1.0) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
  actionpack (4.1.0) lib/action_dispatch/routing/route_set.rb:48:in `call'
  actionpack (4.1.0) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.1.0) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.1.0) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.0) lib/action_dispatch/routing/route_set.rb:676:in `call'
  http_accept_language (2.0.5) lib/http_accept_language/middleware.rb:14:in `call'
  i18n-js (2.1.2) lib/i18n-js/middleware.rb:11:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.5.5) lib/rack/etag.rb:23:in `call'
  rack (1.5.5) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.5) lib/rack/head.rb:11:in `call'
  actionpack (4.1.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.0) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.1.0) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  activerecord (4.1.0) lib/active_record/migration.rb:380:in `call'
  actionpack (4.1.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.0) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.0) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  actionpack (4.1.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.0) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.1.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.0) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.0) lib/action_dispatch/middleware/static.rb:64:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.0) lib/rails/engine.rb:514:in `call'
  railties (4.1.0) lib/rails/application.rb:144:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  rack (1.5.5) lib/rack/content_length.rb:14:in `call'
  rack (1.5.5) lib/rack/handler/webrick.rb:60:in `service'
  /usr/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /usr/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /usr/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

**Comment by tf** [comment]
Try Ruby 2.1 . This appears to be a [problem with ActiveAdmin and Ruby 2.2](https://github.com/activeadmin/activeadmin/issues/3733).

**Comment by dklesev** [comment]
@tf yes, ruby 2.1 seems to solve the issue, thx
