### ISSUE TITLE
Routing Error running Passenger in Production

### ISSUE THREAD

**Issue by marcoreinke** [codevise/pageflow#629]
I've set up Pageflow to run it with Passenger in production.
But trying to access the precompiled production version causes a routing error:

```
I, [2016-09-12T04:28:01.061985 #28437]  INFO -- : Started GET "/" for XX.XX.XXX.X at 2016-09-12 04:28:01 -0400
F, [2016-09-12T04:28:01.064719 #28437] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/"):
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.2/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.2/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:67:in `block in tagged'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:25:in `tagged'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:67:in `tagged'
  vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.2/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'
  vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/engine.rb:511:in `call'
  vendor/bundle/ruby/2.0.0/gems/railties-4.0.2/lib/rails/application.rb:97:in `call'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

Am I doing anything wrong by running

`bundle exec rake app:precompile db:migrate RAILS_ENV=production`

to get Pageflow ready for production?

**Comment by marcoreinke** [comment]
No error. It was my fault ;-)

**Comment by marcoreinke** [comment]
Now I have a routing error when loading stylesheets:

```
I, [2016-09-12T11:40:11.737312 #4717]  INFO -- : Cache digest for pageflow/entries/theming.css: f5757468570669ef0cd507eabb7ea6d3
I, [2016-09-12T11:40:11.737382 #4717]  INFO -- : Cache digest for pageflow/entries/show.css: 495619ee09f5538da008839dec37cf2f
I, [2016-09-12T11:40:11.738114 #4717]  INFO -- : Read fragment views/pageflow/published_entries/pageflow/entries/1-20160727083859000000000-pageflow/revisions/1-20160725070608000000000/495619ee09f5538da008839dec37cf2f (0.1ms)
I, [2016-09-12T11:40:11.778320 #4717]  INFO -- :   Rendered vendor/bundle/ruby/2.1.0/gems/pageflow-0.10.0/app/views/pageflow/file_types/_thumbnails.css.erb (15.1ms)
I, [2016-09-12T11:40:11.780267 #4717]  INFO -- :   Rendered vendor/bundle/ruby/2.1.0/gems/pageflow-0.10.0/app/views/pageflow/entries/_theming.css.erb (0.2ms)
I, [2016-09-12T11:40:11.780980 #4717]  INFO -- : Write fragment views/pageflow/published_entries/pageflow/entries/1-20160727083859000000000-pageflow/revisions/1-20160725070608000000000/495619ee09f5538da008839dec37cf2f (0.5ms)
I, [2016-09-12T11:40:11.781036 #4717]  INFO -- :   Rendered vendor/bundle/ruby/2.1.0/gems/pageflow-0.10.0/app/views/pageflow/entries/show.css.erb (47.9ms)
I, [2016-09-12T11:40:11.781155 #4717]  INFO -- : Completed 200 OK in 72ms (Views: 66.4ms | ActiveRecord: 2.5ms)
I, [2016-09-12T11:40:12.299468 #4717]  INFO -- : Started GET "/stylesheets/pageflow/print_view.css" for 31.24.148.1 at 2016-09-12 11:40:12 +0200
F, [2016-09-12T11:40:12.300278 #4717] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/stylesheets/pageflow/print_view.css"):
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.2/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.2/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.0.2/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.1.0/gems/railties-4.0.2/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:67:in `block in tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:25:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:67:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/railties-4.0.2/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.0.2/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.2/lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.0.2/lib/rails/engine.rb:511:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.0.2/lib/rails/application.rb:97:in `call'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by tf** [comment]
Hi Marco,

Is there a `public/assets/pageflow/print_view.css-...css` file among the precompiled assets on the server? Do you see the corresponding 404 inside the browser dev tools?

Tim
