### ISSUE TITLE
Zencoder responded with errors: There is a limit of 20 outputs per job.

### ISSUE THREAD

**Issue by thy1985** [codevise/pageflow#884]
Hi there,

on a new install (development) during testing of zencoding a video I get in 
log/jobs/development/default.log (Encoding failed in Editor):
Zencoder responded with errors:
There is a limit of 20 outputs per job. If you need more outputs, contact us at help@zencoder.com

Is pageflow requesting > 20 outputs? Can this be limited or do we need to get in touch with Zencoder support?

Thanks a lot in advance!

Cheers

**Comment by thy1985** [comment]
I just found #536 , will check that first. No idea why i didn't find it during my first search. Sorry..

**Comment by tf** [comment]
Please post the ` config.zencoder_options` settings from your `config/initializers/pageflow.rb` file.

**Comment by thy1985** [comment]
hi tf

thanks for your reply, here we go:

```
 # Default options for paperclip attachments which are supposed to
  # use filesystem storage. All options allowed in paperclip has_attached_file
  # calls are allowed.
  config.zencoder_options.merge!(
    :api_key => 'XXXXXXXXXXXXXXXXXXXXXXX',
    :output_bucket => 'de-XXXXX-pageflow-development-out',
    :s3_host_alias => 'de-XXXXpageflow-development-out.s3-website-eu-west-1.amazonaws.com',
    :s3_protocol => 'https',
    :attachments_version => 'v1'
  )
```

Cheers,

**Comment by tf** [comment]
To prevent hitting the limit, you need to disable SMIL outputs. The default setup was [changed in 12.0](https://github.com/codevise/pageflow/commit/101b04224efad87efc75dbf0f7201f59a863df34#diff-fb694f854a462c11323c01668b4c647eR82), but I forgot to add a changelog item for the manual update step. I've [added instructions and explanations](https://github.com/codevise/pageflow/commit/3fdc917624f323021eb16d811adfab8091a3cad3#diff-4ac32a78649ca5bdd8e0ba38b7006a1e) to the 12.0 section of the changelog now. Please take a look if that fixes you issue. Thanks for bringing this up!

**Comment by thy1985** [comment]
thanks tf!

actually now stuff is sent to zencoder and on zencoder side i see an encoding success.

But there is another issue obviously. IN pageflow the encoding process increases until it 80 or 90 percent and then it shows an error. resize log:

```
I, [2017-10-20T16:07:17.982000 #842]  INFO -- : Pageflow::PollZencoderJob - perform for Pageflow::VideoFile 1
I, [2017-10-20T16:07:18.647337 #842]  INFO -- : Pageflow::PollZencoderJob - result pending for Pageflow::VideoFile 1
I, [2017-10-20T16:07:23.670776 #855]  INFO -- : Pageflow::PollZencoderJob - perform for Pageflow::VideoFile 1
I, [2017-10-20T16:07:24.316751 #855]  INFO -- : Pageflow::PollZencoderJob - result pending for Pageflow::VideoFile 1
I, [2017-10-20T16:07:29.337007 #865]  INFO -- : Pageflow::PollZencoderJob - perform for Pageflow::VideoFile 1
I, [2017-10-20T16:07:30.005010 #865]  INFO -- : Pageflow::PollZencoderJob - result pending for Pageflow::VideoFile 1
I, [2017-10-20T16:07:40.029494 #887]  INFO -- : Pageflow::PollZencoderJob - perform for Pageflow::VideoFile 1
I, [2017-10-20T16:07:40.673649 #887]  INFO -- : Pageflow::PollZencoderJob - result pending for Pageflow::VideoFile 1
I, [2017-10-20T16:07:50.698377 #918]  INFO -- : Pageflow::PollZencoderJob - perform for Pageflow::VideoFile 1
E, [2017-10-20T16:08:52.429698 #918] ERROR -- : Pageflow::PollZencoderJob - exception for Pageflow::VideoFile 1: #<Net::OpenTimeout: execution expired>
I, [2017-10-20T16:08:52.429796 #918]  INFO -- : /usr/local/lib/ruby/2.3.0/net/http.rb:880:in `initialize'
I, [2017-10-20T16:08:52.429842 #918]  INFO -- : /usr/local/lib/ruby/2.3.0/net/http.rb:880:in `open'
I, [2017-10-20T16:08:52.429878 #918]  INFO -- : /usr/local/lib/ruby/2.3.0/net/http.rb:880:in `block in connect'
I, [2017-10-20T16:08:52.429913 #918]  INFO -- : /usr/local/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
I, [2017-10-20T16:08:52.429948 #918]  INFO -- : /usr/local/lib/ruby/2.3.0/net/http.rb:878:in `connect'
I, [2017-10-20T16:08:52.429983 #918]  INFO -- : /usr/local/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
I, [2017-10-20T16:08:52.430017 #918]  INFO -- : /usr/local/lib/ruby/2.3.0/net/http.rb:852:in `start'
I, [2017-10-20T16:08:52.430052 #918]  INFO -- : /usr/local/lib/ruby/2.3.0/open-uri.rb:319:in `open_http'
I, [2017-10-20T16:08:52.430086 #918]  INFO -- : /usr/local/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
I, [2017-10-20T16:08:52.430120 #918]  INFO -- : /usr/local/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
I, [2017-10-20T16:08:52.430155 #918]  INFO -- : /usr/local/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
I, [2017-10-20T16:08:52.430189 #918]  INFO -- : /usr/local/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
I, [2017-10-20T16:08:52.430223 #918]  INFO -- : /usr/local/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
I, [2017-10-20T16:08:52.430258 #918]  INFO -- : /usr/local/lib/ruby/2.3.0/open-uri.rb:717:in `open'
I, [2017-10-20T16:08:52.430292 #918]  INFO -- : /usr/local/lib/ruby/2.3.0/open-uri.rb:31:in `open'
I, [2017-10-20T16:08:52.430327 #918]  INFO -- : /usr/local/bundle/gems/paperclip-4.2.4/lib/paperclip/io_adapters/uri_adapter.rb:17:in `download_content'
I, [2017-10-20T16:08:52.430364 #918]  INFO -- : /usr/local/bundle/gems/paperclip-4.2.4/lib/paperclip/io_adapters/uri_adapter.rb:7:in `initialize'
I, [2017-10-20T16:08:52.430399 #918]  INFO -- : /usr/local/bundle/gems/paperclip-4.2.4/lib/paperclip/io_adapters/registry.rb:29:in `new'
I, [2017-10-20T16:08:52.430435 #918]  INFO -- : /usr/local/bundle/gems/paperclip-4.2.4/lib/paperclip/io_adapters/registry.rb:29:in `for'
I, [2017-10-20T16:08:52.430471 #918]  INFO -- : /usr/local/bundle/gems/paperclip-4.2.4/lib/paperclip/attachment.rb:97:in `assign'
I, [2017-10-20T16:08:52.430578 #918]  INFO -- : /usr/local/bundle/gems/paperclip-4.2.4/lib/paperclip/has_attached_file.rb:66:in `block in define_setter'
I, [2017-10-20T16:08:52.430637 #918]  INFO -- : /usr/local/bundle/gems/pageflow-12.0.0.rc7/app/jobs/pageflow/poll_zencoder_job.rb:44:in `fetch_thumbnail'
I, [2017-10-20T16:08:52.430684 #918]  INFO -- : /usr/local/bundle/gems/pageflow-12.0.0.rc7/app/jobs/pageflow/poll_zencoder_job.rb:13:in `block in perform_with_result'
I, [2017-10-20T16:08:52.430718 #918]  INFO -- : /usr/local/bundle/gems/pageflow-12.0.0.rc7/app/jobs/pageflow/poll_zencoder_job.rb:10:in `catch'
I, [2017-10-20T16:08:52.430751 #918]  INFO -- : /usr/local/bundle/gems/pageflow-12.0.0.rc7/app/jobs/pageflow/poll_zencoder_job.rb:10:in `perform_with_result'
I, [2017-10-20T16:08:52.430783 #918]  INFO -- : /usr/local/bundle/gems/state_machine_job-1.0.0/lib/state_machine_job.rb:18:in `perform'
I, [2017-10-20T16:08:52.430817 #918]  INFO -- : /usr/local/bundle/gems/resque-1.25.2/lib/resque/job.rb:227:in `perform'
I, [2017-10-20T16:08:52.430862 #918]  INFO -- : /usr/local/bundle/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'
I, [2017-10-20T16:08:52.430897 #918]  INFO -- : /usr/local/bundle/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'
I, [2017-10-20T16:08:52.430930 #918]  INFO -- : /usr/local/bundle/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'
I, [2017-10-20T16:08:52.430963 #918]  INFO -- : /usr/local/bundle/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'
I, [2017-10-20T16:08:52.430995 #918]  INFO -- : /usr/local/bundle/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>'
I, [2017-10-20T16:08:52.431027 #918]  INFO -- : /usr/local/bundle/gems/rake-12.1.0/lib/rake/task.rb:251:in `block in execute'
I, [2017-10-20T16:08:52.431060 #918]  INFO -- : /usr/local/bundle/gems/rake-12.1.0/lib/rake/task.rb:251:in `each'
I, [2017-10-20T16:08:52.431098 #918]  INFO -- : /usr/local/bundle/gems/rake-12.1.0/lib/rake/task.rb:251:in `execute'
I, [2017-10-20T16:08:52.431131 #918]  INFO -- : /usr/local/bundle/gems/rake-12.1.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
I, [2017-10-20T16:08:52.431163 #918]  INFO -- : /usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
I, [2017-10-20T16:08:52.431196 #918]  INFO -- : /usr/local/bundle/gems/rake-12.1.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
I, [2017-10-20T16:08:52.431228 #918]  INFO -- : /usr/local/bundle/gems/rake-12.1.0/lib/rake/task.rb:181:in `invoke'
I, [2017-10-20T16:08:52.431260 #918]  INFO -- : /usr/local/bundle/gems/rake-12.1.0/lib/rake/application.rb:153:in `invoke_task'
I, [2017-10-20T16:08:52.431292 #918]  INFO -- : /usr/local/bundle/gems/rake-12.1.0/lib/rake/application.rb:109:in `block (2 levels) in top_level'
I, [2017-10-20T16:08:52.431324 #918]  INFO -- : /usr/local/bundle/gems/rake-12.1.0/lib/rake/application.rb:109:in `each'
I, [2017-10-20T16:08:52.431356 #918]  INFO -- : /usr/local/bundle/gems/rake-12.1.0/lib/rake/application.rb:109:in `block in top_level'
I, [2017-10-20T16:08:52.431396 #918]  INFO -- : /usr/local/bundle/gems/rake-12.1.0/lib/rake/application.rb:118:in `run_with_threads'
I, [2017-10-20T16:08:52.431429 #918]  INFO -- : /usr/local/bundle/gems/rake-12.1.0/lib/rake/application.rb:103:in `top_level'
I, [2017-10-20T16:08:52.431534 #918]  INFO -- : /usr/local/bundle/gems/rake-12.1.0/lib/rake/application.rb:81:in `block in run'
I, [2017-10-20T16:08:52.431570 #918]  INFO -- : /usr/local/bundle/gems/rake-12.1.0/lib/rake/application.rb:179:in `standard_exception_handling'
I, [2017-10-20T16:08:52.431602 #918]  INFO -- : /usr/local/bundle/gems/rake-12.1.0/lib/rake/application.rb:78:in `run'
I, [2017-10-20T16:08:52.431634 #918]  INFO -- : /usr/local/bundle/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
I, [2017-10-20T16:08:52.431665 #918]  INFO -- : /usr/local/bundle/bin/rake:17:in `load'
I, [2017-10-20T16:08:52.431696 #918]  INFO -- : /usr/local/bundle/bin/rake:17:in `<main>'
I, [2017-10-20T16:08:52.431756 #918]  INFO -- : Pageflow::PollZencoderJob - result error for Pageflow::VideoFile 1
```

**Comment by tf** [comment]
If you look at the stacktrace, you see that it raises `#<Net::OpenTimeout: execution expired>` coming from `app/jobs/pageflow/poll_zencoder_job.rb:44:in fetch_thumbnail`. 

https://github.com/codevise/pageflow/blob/b2c5e5316a8d93eddf88db103b24af332d155bec/app/jobs/pageflow/poll_zencoder_job.rb#L42-L48

So the request to download the thumbnail from the output bucket times out. Looking at you `zencoder_options` above, I see that you try to use `https` as `s3_protocol` with an S3 website endpoint as `s3_host_alias`. That cannot work since S3 does not support HTTPS. So the requests time out.

**Comment by tf** [comment]
Make sure to restart the resque workers after changing the config (and be sure there are no unexpected resque worker processes still running in the background)

**Comment by thy1985** [comment]
oh man! Thanks for the pointer. I managed to copy that from another instance where we do not use S3 to serve the content (but an ordinary https after we synced down from S3) and this one supports https... It finally works. You made my day, thanks again!

**Comment by CleverMobile2811** [comment]
Hi everyone.
Nice to  meet you!

I have a problem in pageflow development.
Image upload to aws3 and checking in publish is working well.
But for video, it says "Successfully uploaded", but still "0% Encoding in progress".
As a result, can't select video in edit of page.
Please reply this ticket if you had ever same issue before.
